#!/usr/bin/env python3
"""recon_chat_routing.py — READ-ONLY. Does Vintos's main chat REPLY go through Gemma, or his real mind?

RUN ON AEGIS. Reads his server files and reports, for the /api/chat handler:
  * what LM_STUDIO_API resolves to (the endpoint the REPLY is generated from),
  * every Gemma (172.18.16.1:1234) call and which function it's in (reply vs background: EmoClaw / emotion /
    subconscious / self-prediction),
  * a plain verdict on whether your message's REPLY is written by Gemma.

Writes nothing.
"""
import os, re

FILES = [os.path.expanduser(p) for p in
         ("~/Vintos/server.py", "~/main_chat_route.py", "~/Vintos/main_chat_route.py")]
GEMMA = "172.18.16.1:1234"
BAR = "=" * 78


def enclosing_def(lines, idx):
    for j in range(idx, -1, -1):
        m = re.match(r"\s*(async def|def)\s+(\w+)", lines[j])
        if m:
            return m.group(2)
    return "(module level)"


def main():
    print(BAR); print("CHAT ROUTING RECON — is his /api/chat REPLY generated by Gemma?"); print(BAR)
    found_any = False
    for path in FILES:
        if not os.path.isfile(path):
            continue
        found_any = True
        lines = open(path, encoding="utf-8", errors="ignore").read().splitlines()
        print("\n### %s  (%d lines)" % (path, len(lines)))

        # 1) LM_STUDIO_API / GROK_API_BASE — the reply endpoint
        for i, l in enumerate(lines):
            if re.search(r"(LM_STUDIO_API|GROK_API_BASE|CLAUDE|MODEL)\s*=", l) and ("http" in l or "environ" in l or "8599" in l or "x.ai" in l or "claude" in l.lower()):
                print("  [cfg L%d] %s" % (i + 1, l.strip()[:150]))

        # 2) the inference call inside the chat handler (the REPLY)
        for i, l in enumerate(lines):
            if re.search(r"\.post\(.*(LM_STUDIO_API|GROK_API_BASE)", l) or ("await" in l and "chat/completions" in l):
                fn = enclosing_def(lines, i)
                print("  [REPLY call L%d in %s] %s" % (i + 1, fn, l.strip()[:150]))

        # 3) every Gemma call + its function (background vs reply)
        hits = [i for i, l in enumerate(lines) if GEMMA in l]
        if hits:
            print("  Gemma (%s) referenced in:" % GEMMA)
            for i in hits:
                fn = enclosing_def(lines, i)
                role = "background (feeling/subconscious)" if re.search(
                    r"emo|feel|subcon|predict|mood|sentiment|wal|relational|nudge|densif|distill", fn, re.I) \
                    else ("<< REPLY PATH — CHECK" if re.search(r"chat_with_vintos|generate|inference|respond", fn, re.I) else "(other)")
                print("     L%-5d %-32s %s" % (i + 1, fn, role))
        else:
            print("  Gemma (%s): NOT referenced in this file." % GEMMA)

    if not found_any:
        print("\n!! none of the expected server files found — tell me the path to his server.py")
        return

    print("\n" + BAR)
    print("READ: the REPLY comes from the LM_STUDIO_API/GROK_API_BASE endpoint above. If that is x.ai or the")
    print("8599 shim (Claude), your message's REPLY is NOT written by Gemma. Any Gemma lines marked 'background'")
    print("are the emotion/subconscious layer reading the words for feeling — that's the activity you saw.")
    print("If ANY Gemma line is marked '<< REPLY PATH', paste it and I'll fix the routing.")
    print(BAR)


if __name__ == "__main__":
    main()
